#!/usr/bin/env python
# -*- coding: utf-8 -*-

def pokedex():
    #This dictionary contains the name and types information of every pokemon from the first generation.
    #Informations taken from http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_Kanto_Pok%C3%A9dex_number
    pokedex = {'Bulbasaur': 'Grass Poison',
               'Ivysaur': 'Grass Poison',
               'Venusaur': 'Grass Poison',
               'Charmander': 'Fire Blank',
               'Charmeleon': 'Fire Blank',
               'Charizard': 'Fire Flying',
               'Squirtle': 'Water Blank',
               'Wartortle': 'Water Blank',
               'Blastoise': 'Water Blank',
               'Caterpie': 'Bug Blank',
               'Metapod': 'Bug Blank',
               'Butterfree': 'Bug Flying',
               'Weedle': 'Bug Poison',
               'Kakuna': 'Bug Poison',
               'Beedrill': 'Bug Poison',
               'Pidgey': 'Normal Flying',
               'Pidgeotto': 'Normal Flying',
               'Pidgeot': 'Normal Flying',
               'Rattata': 'Normal Blank',
               'Raticate': 'Normal Blank',
               'Spearow': 'Normal Flying',
               'Fearow': 'Normal Flying',
               'Ekans': 'Poison Blank',
               'Arbok': 'Poison Blank',
               'Pikachu': 'Electric Blank',
               'Raichu': 'Electric Blank',
               'Sandshrew': 'Ground Blank',
               'Sandslash': 'Ground Blank',
               'Nidoran Female': 'Poison Blank',
               'Nidorina': 'Poison Blank',
               'Nidoqueen': 'Poison Ground',
               'Nidoran Male': 'Poison Blank',
               'Nidorino': 'Poison Blank',
               'Nidoking': 'Poison Ground',
               'Clefairy': 'Normal Blank',
               'Clefable': 'Normal Blank',
               'Vulpix': 'Fire Blank',
               'Ninetales': 'Fire Blank',
               'Jigglypuff': 'Normal Blank',
               'Wigglytuff': 'Normal Blank',
               'Zubat': 'Poison Flying',
               'Golbat': 'Poison Flying',
               'Oddish': 'Grass Poison',
               'Gloom': 'Grass Poison',
               'Vileplume': 'Grass Poison',
               'Paras': 'Bug Grass',
               'Parasect': 'Bug Grass',
               'Venonat': 'Bug Poison',
               'Venomoth': 'Bug Poison',
               'Diglett': 'Ground Blank',
               'Dugtrio': 'Ground Blank',
               'Meowth': 'Normal Blank',
               'Persian': 'Normal Blank',
               'Psyduck': 'Water Blank',
               'Golduck': 'Water Blank',
               'Mankey': 'Fighting Blank',
               'Primeape': 'Fighting Blank',
               'Growlithe': 'Fire Blank',
               'Arcanine': 'Fire Blank',
               'Poliwag': 'Water Blank',
               'Poliwhirl': 'Water Blank',
               'Poliwrath': 'Water Fighting',
               'Abra': 'Psychic Blank',
               'Kadabra': 'Psychic Blank',
               'Alakazam': 'Psychic Blank',
               'Machop': 'Fighting Blank',
               'Machoke': 'Fighting Blank',
               'Machamp': 'Fighting Blank',
               'Bellsprout': 'Grass Poison',
               'Weepinbell': 'Grass Poison',
               'Victreebel': 'Grass Poison',
               'Tentacool': 'Water Poison',
               'Tentacruel': 'Water Poison',
               'Geodude': 'Rock Ground',
               'Graveler': 'Rock Ground',
               'Golem': 'Rock Ground',
               'Ponyta': 'Fire Blank',
               'Rapidash': 'Fire Blank',
               'Slowpoke': 'Water Psychic',
               'Slowbro': 'Water Psychic',
               'Magnemite': 'Electric, Steel',
               'Magneton': 'Electric Steel',
               'Farfetch\'d': 'Normal Flying',
               'Doduo': 'Normal Flying',
               'Dodrio': 'Normal Flying',
               'Seel': 'Water Blank',
               'Dewgong': 'Water Ice',
               'Grimer': 'Poison Blank',
               'Muk': 'Poison Blank',
               'Shellder': 'Water Blank',
               'Cloyster': 'Water Ice',
               'Gastly': 'Ghost Poison',
               'Haunter': 'Ghost Poison',
               'Gengar': 'Ghost Poison',
               'Onix': 'Rock Ground',
               'Drowzee': 'Psychic Blank',
               'Hypno': 'Psychic Blank',
               'Krabby': 'Water Blank',
               'Kingler': 'Water Blank',
               'Voltorb': 'Electric Blank',
               'Electrode': 'Electric Blank',
               'Exeggcute': 'Grass Psychic',
               'Exeggutor': 'Grass Psychic',
               'Cubone': 'Ground Blank',
               'Marowak': 'Ground Blank',
               'Hitmonlee': 'Fighting Blank',
               'Hitmonchan': 'Fighting Blank',
               'Lickitung': 'Normal Blank',
               'Koffing': 'Poison Blank',
               'Weezing': 'Poison Blank',
               'Rhyhorn': 'Ground Rock',
               'Rhydon': 'Ground Rock',
               'Chansey': 'Normal Blank',
               'Tangela': 'Grass Blank',
               'Kangaskhan': 'Normal Blank',
               'Horsea': 'Water Blank',
               'Seadra': 'Water Blank',
               'Goldeen': 'Water Blank',
               'Seaking': 'Water Blank',
               'Staryu': 'Water Blank',
               'Starmie': 'Water Psychic',
               'Mr. Mime': 'Psychic Blank',
               'Scyther': 'Bug Flying',
               'Jynx': 'Ice Psychic',
               'Electabuzz': 'Electric Blank',
               'Magmar': 'Fire Blank',
               'Pinsir': 'Bug Blank',
               'Tauros': 'Normal Blank',
               'Magikarp': 'Water Normal',
               'Gyarados': 'Water Flying',
               'Lapras': 'Water Ice',
               'Ditto': 'Normal Blank',
               'Eevee': 'Normal Blank',
               'Vaporeon': 'Water Blank',
               'Jolteon': 'Electric Blank',
               'Flareon': 'Fire Blank',
               'Porygon': 'Normal Blank',
               'Omanyte': 'Rock Water',
               'Omastar': 'Rock Water',
               'Kabuto': 'Rock Water',
               'Kabutops': 'Rock Water',
               'Aerodactyl': 'Rock Flying',
               'Snorlax': 'Normal Blank',
               'Articuno': 'Ice Flying',
               'Zapdos': 'Electric Flying',
               'Moltres': 'Fire Flying',
               'Dratini': 'Dragon Blank',
               'Dragonair': 'Dragon Blank',
               'Dragonite': 'Dragon Flying',
               'Mewtwo': 'Psychic Blank',
               'Mew': 'Psychic Blank'}
    return pokedex


def poketype():
    poketype = {'Normal': 0, 'Fight': 1, 'Flying': 2,
                'Poison': 3, 'Ground': 4, 'Rock': 5,
                'Bug': 6, 'Ghost': 7, 'Steel': 8,
                'Fire': 9, 'Water': '10', 'Grass': 11,
                'Electric': 12, 'Psychic': '13', 'Ice': 14,
                'Dragon': 15, 'Dark': 16, 'Fairy': 17}
    return poketype


def poke_type_chart():
    type_chart = [
            [1, 1, 1, 1, 1, 0.5, 1, 0, 1.5, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [2, 1, 0.5, 0.5, 1, 2, 0.5, 0, 2, 1, 1, 1, 1, 0.5, 2, 1, 2, 0.5],
            [1, 2, 1, 1, 1, 0.5, 2, 1, 0.5, 1, 1, 2, 0.5, 1, 1, 1, 1, 1],
            [1, 1, 1, 0.5, 0.5, 0.5, 1, 0.5, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2],
            [1, 1, 0, 2, 1, 2, 0.5, 1, 2, 2, 1, 0.5, 2, 1, 1, 1, 1, 1],
            [1, 0.5, 2, 1, 0.5, 1, 2, 1, 0.5, 2, 1, 1, 1, 1, 2, 1, 1, 1],
            [1, 0.5, 0.5, 0.5, 1, 1, 1, 0.5, 0.5, 0.5, 1, 2, 1, 2, 1, 1, 2, 0.5],
            [0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0.5, 1],
            [1, 1, 1, 1, 1, 2, 1, 1, 0.5, 0.5, 0.5, 1, 0.5, 1, 2, 1, 1, 2],
            [1, 1, 1, 1, 1, 0.5, 2, 1, 2, 0.5, 0.5, 2, 1, 1, 2, 0.5, 1, 1],
            [1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 0.5, 0.5, 1, 1, 1, 0.5, 1,1],
            [1, 1, 0.5, 0.5,2,2, 0.5, 1, 0.5, 0.5, 2, 0.5, 1, 1, 1, 0.5, 1, 1],
            [1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 0.5, 0.5, 1, 1, 0.5, 1, 1],
            [1, 2, 1, 2, 1, 1, 1, 1, 0.5, 1, 1, 1, 1, 0.5, 1, 1, 0, 1],
            [1, 1, 2, 1, 2, 1,  1, 1, 0.5, 0.5, 0.5, 2, 1, 1, 0.5, 2, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 0.5, 1, 1, 1, 1, 1, 1, 2, 1, 0],
            [1, 0.5, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0.5, 0.5],
            [1, 2, 1, 0.5, 1, 1, 1, 1, 0.5, 0.5, 1, 1, 1, 1, 1, 2, 2, 1]
            ]
    return type_chart


def pokemon_choice(pokemon_name):
    pkmn_list = pokedex()
    for i in pkmn_list:
        if i == pokemon_name:
            return {i: pkmn_list[i]}
    return None
